"""Narrative training metadata merged into packaged scenarios at load time."""

from __future__ import annotations

SCENARIO_DETAILS: dict[str, dict[str, object]] = {
    "dsc_distress_simple": {
        "description": "Your vessel has an immediate emergency. Send a DSC distress alert, then prepare for the voice distress follow-up on Channel 16.",
        "situation": "Your vessel BLUE MERIDIAN has smoke in the engine compartment. The crew is preparing to evacuate and immediate assistance is required.",
        "context": {
            "what_is_happening": "BLUE MERIDIAN has an onboard fire and evacuation is being prepared.",
            "concerns": "your vessel",
            "user_role": "skipper operating the VHF/DSC set",
            "known_vessels": ["BLUE MERIDIAN"],
            "position": "25 48N, 080 12W near Harbor Point",
            "risk_level": "distress",
            "current_objective": "Send a DSC distress alert and establish Channel 16 readiness.",
        },
        "initial_conditions": [
            "Radio is off at scenario start.",
            "GPS position is available.",
            "Smoke is visible and the crew is preparing lifejackets.",
        ],
        "incoming_events": ["SYSTEM: Engine-room smoke report received from crew."],
        "required_assessment": "This is grave and imminent danger to your vessel, so distress priority is correct.",
        "correct_procedure": "Power on, use Channel 16 readiness, open the protected distress cover, hold the distress control, then confirm Channel 16.",
        "expected_message_elements": ["vessel name", "position", "nature of distress", "assistance required"],
        "possible_wrong_actions": ["Sending urgency instead of distress", "pressing distress with the cover closed", "trying to speak on Channel 70"],
        "final_explanation": "A DSC distress alert is appropriate because the emergency threatens life and vessel safety immediately.",
    },
    "mayday_voice": {
        "description": "Make a complete voice MAYDAY call for your vessel after recognizing grave and imminent danger.",
        "situation": "Your vessel BLUE MERIDIAN is taking on water after striking debris. The bilge pump is losing ground and help is needed immediately.",
        "context": {
            "what_is_happening": "BLUE MERIDIAN is flooding and may need evacuation.",
            "concerns": "your vessel",
            "user_role": "radio operator making the distress call",
            "known_vessels": ["BLUE MERIDIAN", "COASTGUARD"],
            "position": "25 48N, 080 12W",
            "risk_level": "distress",
            "current_objective": "Transmit a clear MAYDAY voice call on Channel 16.",
        },
        "initial_conditions": ["Radio starts off.", "Channel 16 is the distress and calling channel.", "Crew is controlling flooding but needs urgent help."],
        "incoming_events": ["SYSTEM: Flooding report escalated to grave and imminent danger."],
        "required_assessment": "Use MAYDAY because life and vessel are in immediate danger.",
        "correct_procedure": "Power on, switch to Channel 16, press PTT, speak the MAYDAY structure, then release PTT.",
        "expected_message_elements": ["MAYDAY repeated", "vessel name", "position", "nature of distress", "assistance required", "persons onboard"],
        "possible_wrong_actions": ["Using Pan-Pan", "omitting position", "holding PTT without speaking", "transmitting before selecting Channel 16"],
        "final_explanation": "The priority signal must match the danger: flooding with possible abandonment is a MAYDAY situation.",
    },
    "mayday_relay": {
        "description": "Relay another vessel's MAYDAY when no coast station appears to respond.",
        "situation": "Vessel SELENA has transmitted MAYDAY twice. You hear no coast station acknowledgement and SELENA is weak but readable.",
        "context": {
            "what_is_happening": "Another vessel may be in distress and has not been acknowledged.",
            "concerns": "another vessel",
            "user_role": "nearby vessel deciding whether to relay",
            "known_vessels": ["SELENA", "BLUE MERIDIAN", "COASTGUARD"],
            "position": "SELENA reported 3 NM east of Harbor Point",
            "risk_level": "distress relay",
            "current_objective": "Listen first, then relay the MAYDAY if no authority responds.",
        },
        "initial_conditions": ["Radio starts off.", "A weak MAYDAY from SELENA has been heard.", "No coast station acknowledgement has been heard."],
        "incoming_events": ["OTHER VESSEL: MAYDAY, MAYDAY, MAYDAY. This is SELENA..."],
        "required_assessment": "Relay only because the distress call appears unacknowledged and you can assist communications.",
        "correct_procedure": "Power on, monitor Channel 16, hold PTT, transmit MAYDAY RELAY with SELENA's details, then release.",
        "expected_message_elements": ["MAYDAY RELAY", "distressed vessel name", "reported position", "nature of distress if known", "your vessel identity"],
        "possible_wrong_actions": ["Transmitting over an acknowledgement", "changing away from Channel 16", "treating the call as routine"],
        "final_explanation": "A relay is justified when a distress call is not acknowledged and you can help get it to a coast station.",
    },
    "panpan_engine": {
        "description": "Make an urgency call for engine failure without immediate danger to life.",
        "situation": "BLUE MERIDIAN has lost propulsion near a traffic channel but is not taking water and no one is injured.",
        "context": {
            "what_is_happening": "Engine failure has left your vessel restricted in maneuverability near traffic.",
            "concerns": "your vessel",
            "user_role": "skipper requesting urgent assistance",
            "known_vessels": ["BLUE MERIDIAN", "COASTGUARD"],
            "position": "near Harbor Point channel entrance",
            "risk_level": "urgency",
            "current_objective": "Send a Pan-Pan call with position and assistance needed.",
        },
        "initial_conditions": ["Radio starts off.", "There is no immediate danger to life.", "Traffic is nearby."],
        "incoming_events": ["SYSTEM: Engine alarm and loss of propulsion confirmed."],
        "required_assessment": "Use Pan-Pan because assistance is urgent but not a grave and imminent danger.",
        "correct_procedure": "Power on, select Channel 16, hold PTT, speak the Pan-Pan message, release PTT.",
        "expected_message_elements": ["PAN-PAN repeated", "station called", "vessel name", "position", "problem", "assistance requested"],
        "possible_wrong_actions": ["Using MAYDAY without grave danger", "making a routine call", "omitting position"],
        "final_explanation": "Urgency priority alerts other stations without overstating the emergency.",
    },
    "panpan_medical": {
        "description": "Make an urgency call for a medical emergency where immediate advice or evacuation may be needed.",
        "situation": "A crew member aboard BLUE MERIDIAN has chest pain and shortness of breath. The vessel is stable but medical help is urgent.",
        "context": {
            "what_is_happening": "A serious medical problem requires urgent radio assistance.",
            "concerns": "your vessel",
            "user_role": "radio operator requesting medical assistance",
            "known_vessels": ["BLUE MERIDIAN", "COASTGUARD"],
            "position": "25 48N, 080 12W",
            "risk_level": "urgency",
            "current_objective": "Transmit a Pan-Pan medical urgency call.",
        },
        "initial_conditions": ["Radio starts off.", "Patient is conscious.", "No immediate vessel danger exists."],
        "incoming_events": ["SYSTEM: Crew reports chest pain and asks for medical advice."],
        "required_assessment": "Use Pan-Pan for urgent medical assistance unless the situation becomes immediately life-threatening.",
        "correct_procedure": "Power on, use Channel 16, transmit Pan-Pan with medical details and position.",
        "expected_message_elements": ["PAN-PAN", "medical problem", "position", "assistance requested", "persons onboard"],
        "possible_wrong_actions": ["Using routine call priority", "sharing irrelevant details", "forgetting the position"],
        "final_explanation": "Medical urgency requires priority handling while keeping the message concise.",
    },
    "securite_hazard": {
        "description": "Broadcast a safety message about a floating hazard to navigation.",
        "situation": "You sight a large floating timber hazard near the channel entrance. It is dangerous to navigation but no vessel is in immediate distress.",
        "context": {
            "what_is_happening": "A navigation hazard needs to be broadcast to nearby traffic.",
            "concerns": "nearby vessels",
            "user_role": "vessel reporting a safety hazard",
            "known_vessels": ["BLUE MERIDIAN", "all stations"],
            "position": "near Harbor Point channel entrance",
            "risk_level": "safety",
            "current_objective": "Send a Securite safety message.",
        },
        "initial_conditions": ["Radio starts off.", "Hazard position is known approximately.", "No immediate distress exists."],
        "incoming_events": ["SYSTEM: Lookout reports floating timber crossing the channel."],
        "required_assessment": "Use Securite for important navigational safety information.",
        "correct_procedure": "Power on, call on Channel 16, make the safety announcement, and move details to a working channel if appropriate.",
        "expected_message_elements": ["SECURITE", "all stations", "hazard type", "position", "time observed"],
        "possible_wrong_actions": ["Using MAYDAY or Pan-Pan", "failing to state the hazard position", "blocking Channel 16 with long detail"],
        "final_explanation": "Safety messages warn traffic without claiming urgency or distress.",
    },
    "receiving_call": {
        "description": "Receive an incoming call, acknowledge briefly, and move to a working channel without blocking Channel 16.",
        "situation": "Vessel MARLIN calls BLUE MERIDIAN on Channel 16 to coordinate passing. You need to acknowledge and shift to Channel 72.",
        "context": {
            "what_is_happening": "A nearby vessel is calling you for a routine passing arrangement.",
            "concerns": "your vessel and another vessel",
            "user_role": "called station responding to a routine call",
            "known_vessels": ["BLUE MERIDIAN", "MARLIN"],
            "position": "Harbor Point fairway",
            "risk_level": "routine",
            "current_objective": "Acknowledge and move to a working channel.",
        },
        "initial_conditions": ["Radio starts off.", "Incoming call is heard on Channel 16.", "Channel 72 is available as a working channel."],
        "incoming_events": ["OTHER VESSEL: BLUE MERIDIAN, BLUE MERIDIAN, this is MARLIN on one-six."],
        "required_assessment": "This is routine traffic. Keep Channel 16 clear and move to a working channel.",
        "correct_procedure": "Power on, answer briefly, agree to switch to Channel 72, then set the working channel.",
        "expected_message_elements": ["called vessel", "calling vessel", "acknowledgement", "working channel"],
        "possible_wrong_actions": ["Conducting the full conversation on Channel 16", "using distress priority", "changing channel without acknowledging"],
        "final_explanation": "Routine calls should be acknowledged briefly before moving away from Channel 16.",
    },
    "routine_radio_check": {
        "description": "Make a concise routine radio check without using distress or urgency language.",
        "situation": "Before leaving Harbor Point, BLUE MERIDIAN needs a brief radio check with the marina.",
        "context": {
            "what_is_happening": "You are confirming your radio works before departure.",
            "concerns": "your vessel",
            "user_role": "operator making a routine check",
            "known_vessels": ["BLUE MERIDIAN", "HARBOR POINT MARINA"],
            "position": "Harbor Point marina basin",
            "risk_level": "routine",
            "current_objective": "Make a short routine radio check.",
        },
        "initial_conditions": ["Radio starts off.", "No emergency exists.", "Keep the call short."],
        "incoming_events": [],
        "required_assessment": "This is routine traffic; do not use priority signals.",
        "correct_procedure": "Power on, select the calling channel, make a short radio check, then release PTT.",
        "expected_message_elements": ["station called", "your vessel name", "radio check request"],
        "possible_wrong_actions": ["Using MAYDAY or Pan-Pan", "making a long transmission", "forgetting to release PTT"],
        "final_explanation": "Routine calls should be brief and should not imply urgency.",
    },
    "marina_call": {
        "description": "Call the marina for berthing instructions and keep the exchange routine.",
        "situation": "BLUE MERIDIAN is approaching Harbor Point Marina and needs berthing instructions.",
        "context": {
            "what_is_happening": "You need routine marina coordination before entering.",
            "concerns": "your vessel",
            "user_role": "operator calling a marina",
            "known_vessels": ["BLUE MERIDIAN", "HARBOR POINT MARINA"],
            "position": "outside Harbor Point Marina",
            "risk_level": "routine",
            "current_objective": "Call the marina and request berthing instructions.",
        },
        "initial_conditions": ["Radio starts off.", "No safety issue exists.", "Marina working channel may be assigned after contact."],
        "incoming_events": [],
        "required_assessment": "Use routine calling and keep Channel 16 clear after contact.",
        "correct_procedure": "Power on, make the routine call, then move to the assigned working channel if directed.",
        "expected_message_elements": ["marina name", "vessel name", "request for berth or instructions"],
        "possible_wrong_actions": ["Using a priority signal", "omitting vessel name", "continuing long traffic on Channel 16"],
        "final_explanation": "Marina calls are routine and should be concise.",
    },
    "ship_to_ship": {
        "description": "Coordinate a ship-to-ship passing arrangement and move routine details off the calling channel.",
        "situation": "BLUE MERIDIAN and MARLIN are converging near a bend in the fairway and need a clear passing agreement.",
        "context": {
            "what_is_happening": "Two vessels need a routine passing arrangement.",
            "concerns": "your vessel and another vessel",
            "user_role": "operator coordinating navigation intentions",
            "known_vessels": ["BLUE MERIDIAN", "MARLIN"],
            "position": "Harbor Point fairway bend",
            "risk_level": "routine",
            "current_objective": "Make a clear routine call and agree a working channel.",
        },
        "initial_conditions": ["Radio starts off.", "No distress exists.", "Both vessels are maneuvering."],
        "incoming_events": ["OTHER VESSEL: MARLIN visible ahead near the bend."],
        "required_assessment": "Use routine procedure and avoid cluttering Channel 16.",
        "correct_procedure": "Power on, call the vessel, exchange short passing details, then release PTT.",
        "expected_message_elements": ["other vessel name", "your vessel name", "passing intention", "working channel if needed"],
        "possible_wrong_actions": ["Using priority language", "talking over another vessel", "giving unclear intentions"],
        "final_explanation": "Routine navigation coordination needs clarity and radio discipline.",
    },
}
